// <auto-generated />
using System;
using FlyingEye.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace FlyingEye.Migrations
{
    [DbContext(typeof(VulnerablePartsServiceDbContext))]
    [Migration("20251126123118_AddRecordTable")]
    partial class AddRecordTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlyingEye.Spacers.SpacerValidationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ABSite")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AT11Width")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BigCoatingWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("ModelPn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmallCoatingWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhiteSpaceWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "ABSite")
                        .IsUnique()
                        .HasDatabaseName("IX_SpacerValidationData_ResourceId_ABSite");

                    b.ToTable("AppSpacerValidationData", (string)null);
                });

            modelBuilder.Entity("FlyingEye.Spacers.SpacerValidationDataRecordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ABSite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AT11Width")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BigCoatingWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("ModelPn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmallCoatingWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhiteSpaceWidth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppSpacerValidationDataRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
